#!/bin/bash

git clone git+ssh://git@github.com/maryvilledev/RunestoneComponents.git
cp build/codesplain.js RunestoneComponents/runestone/codesplain/js/
cp build/codesplain.css RunestoneComponents/runestone/codesplain/css/
cd RunestoneComponents
git add .
git status
git commit -m "circle build $CIRCLE_SHA1" --author="CircleCI <>" # This will prevent git prompting for credentials
git remote set-url origin git+ssh://git@github.com/maryvilledev/RunestoneComponents.git
git push origin master

exit

