#!/bin/bash

git clone git@github.com:maryvilledev/RunestoneComponents.git
cp build/codesplain.js RunestoneComponents/runestone/codesplain/js/
cd RunestoneComponents
git add .
git commit -m "circle build $CIRCLE_SHA1"
git remote set-url origin git+ssh://git@github.com/maryvilledev/RuneStonComponents.git
git push origin master
cd ..
