#!/bin/bash

git clone https://github.com/maryvilledev/RunestoneComponents.git
cp build/codesplain.js RunestoneComponents/runestone/codesplain/js/
cd RunestoneComponents
git add .
git commit -m "circle build $CIRCLE_SHA1"
git push origin master
cd ..
